# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Testes e Integração Contínua
author: Desenvolvido no ambito da cadeira de MDS 2019/20 @ISEC
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  A Bootstrap 4 start up project for Jekyll and Github Pages
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

repository: "nasa72/mds-trabalho3_1920"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Lista de páginas para o menu (A ordem da lista é a ordem pela qual aparecem)
header_pages:
    - _pages/integracao_continua.md
    - _pages/testes_automaticos.md
    - _pages/tools.md
    - _pages/quiz.md
    - _pages/suporte.md
    - _pages/acercade.md  
    
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - node_modules
  - README.md
  - LICENSE.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - package.json
  - script
  - spec
  - vendor
  - update_boostrap.sh
  
include:
    - _pages
